[package]
name = "cks-dec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soundtouch-sys = {version = "*", optional = true}

[features]
default = []
time-stretch = ["soundtouch-sys"]
